import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} antialiased`}>
      <body
        suppressHydrationWarning={true}
        className="min-h-screen overflow-x-hidden bg-bg-default font-sans text-text-default text-sm"
      >
        <Navbar />
        <NuqsAdapter> {children}</NuqsAdapter>
        <Footer />
      </body>
    </html>
  );
}
