import {
  parseAsArrayOf,
  parseAsBoolean,
  parseAsInteger,
  parseAsString,
  parseAsStringEnum,
} from "nuqs";

import { SoldStatusType, StatusType } from "./type";

export const defaultPropertyFilters = {
  property_type: "",
  location: "",
  sort: "newest",
  page: 1,
  beds: 0,
  baths: 0,
  sold_status: SoldStatusType.SALE,
  status: StatusType.ANY,
  house_type: [] as string[],
  tour_type: [] as string[],
  day_on_platform: "",
  min_sqft: "",
  max_sqft: "",
  min_lot: "",
  max_lot: "",
  min_age: "",
  max_age: "",
  hoa_fee: "",
  garage: 0,
  stories: 0,
  interiors: [] as string[],
  exteriors: [] as string[],
  views: [] as string[],
  keywords: [] as string[],
  min_price: 0,
  max_price: 10000000,
  is_price_drop: false,
};

export const filterParsers = {
  property_type: parseAsString.withDefault(""),
  location: parseAsString.withDefault(""),
  sort: parseAsString.withDefault("newest"),
  page: parseAsInteger.withDefault(1),
  beds: parseAsInteger.withDefault(0),
  baths: parseAsInteger.withDefault(0),
  sold_status: parseAsStringEnum<SoldStatusType>(
    Object.values(SoldStatusType),
  ).withDefault(SoldStatusType.SALE),
  status: parseAsStringEnum<StatusType>(Object.values(StatusType)).withDefault(
    StatusType.ANY,
  ),
  house_type: parseAsArrayOf(parseAsString).withDefault([]),
  tour_type: parseAsArrayOf(parseAsString).withDefault([]),
  day_on_platform: parseAsString.withDefault(""),
  min_sqft: parseAsString.withDefault(""),
  max_sqft: parseAsString.withDefault(""),
  min_lot: parseAsString.withDefault(""),
  max_lot: parseAsString.withDefault(""),
  min_age: parseAsString.withDefault(""),
  max_age: parseAsString.withDefault(""),
  hoa_fee: parseAsString.withDefault(""),
  garage: parseAsInteger.withDefault(0),
  stories: parseAsInteger.withDefault(0),
  interiors: parseAsArrayOf(parseAsString).withDefault([]),
  exteriors: parseAsArrayOf(parseAsString).withDefault([]),
  views: parseAsArrayOf(parseAsString).withDefault([]),
  keywords: parseAsArrayOf(parseAsString).withDefault([]),
  min_price: parseAsInteger.withDefault(0),
  max_price: parseAsInteger.withDefault(10000000),
  is_price_drop: parseAsBoolean.withDefault(false),
};
